services:
  speaches:
    container_name: speaches
    restart: unless-stopped
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    volumes:
      - hf-hub-cache:/home/ubuntu/.cache/huggingface/hub
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  hf-hub-cache:
    external: true
